### ISSUE TITLE
Scheduler component do not provide UI option to set scheduling frequency

### ISSUE THREAD

**Issue by macrocks** [mulesoft/docs-code-builder#299] opened 2024-04-23 20:46 UTC
Hi Team,

I was trying to develop an integration or api which has a scheduler and run a flow with fixed frequency. When I added scheduler and look for UI option set frequency it doesn't provide me any option.

As well as on XML when space pressed it is not giving auto populate  for scheduling frequency .
<img width="746" alt="image" src="https://github.com/mulesoft/docs-code-builder/assets/14057216/26e92aa7-660e-4925-b5f0-c9a273c5e916">

**Comment by valkyrie69** [comment] 2024-04-24 23:46
@macrocks  There are examples for how to configure the scheduling strategy here:
https://docs.mulesoft.com/anypoint-code-builder/acb-component-scheduler
Configuration is not yet available in the UI, but will be in a future release.

**Comment by valkyrie69** [comment] 2024-05-01 15:04
I'm closing this issue. If the issue isn't resolved, please re-open and add more specific details about the documentation issue you are encountering. This repository is for reporting issues with the documentation (not the software).

**Closed as completed by valkyrie69** 2024-05-01 15:04 UTC
